version: "3.3"
services:
  test_import:
    build: .
    command: Command=import InputFilename=/data/test.json DatabaseMapping:2=2
    volumes:
    - type: volume
      source: data
      target: /data


volumes:
  data:
